[package]
name = "graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "graph"

[dependencies]
thiserror = "*"
# itertools = "*"

[dev-dependencies]
graph_derive = { path = "../graph_derive" }